name="personal-ai"
main="src/index.ts"

compatibility_date = "2022-11-22"

kv_namespaces = [
    { binding = "personal_ai_chats", id = "7f1b61b5c1bb4b03a8eba5130ecef4d3", preview_id = "1d6199716dc046ac9ffe41e17f4a1d80"}
]
